version: "3.8"
services:
  kapped-ai-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules

  vite-sandbox:
    build:
      context: ./vite-template
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    volumes:
      - ./vite-template:/app
      - /app/node_modules
