name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm typecheck
      - run: pnpm test
      - run: pnpm --prefix sandbox-vite install
      - run: pnpm --prefix sandbox-vite build
      - uses: actions/upload-artifact@v4
        with:
          name: sandbox-vite-dist
          path: sandbox-vite/dist
          if-no-files-found: error

